### ISSUE TITLE
Object#timeout is deprecated, use Timeout.timeout instead

### ISSUE THREAD

**Issue by thomasriley** [sensu-plugins/sensu-plugins-logstash#10]
I get the below error when using logstash-handler with Sensu 0.25.1:

`block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.\n/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in`block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.\n/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.\n"]}

Seems this was fixed in a recent commit to sensu-plugin. 
As the gemspec does not appear to pin a version of sensu-plugin, guessing sensu-plugins-logstash requires a new build to pull this updated dependancy in?

**Comment by cwjohnston** [comment]
@thomasriley version 0.1.0 is now available on RubyGems and is compatable with newer releases of sensu-plugin which resolve the timeout deprecation warning you describe.
