### ISSUE TITLE
Monitoring API response format was changed at v6

### ISSUE THREAD

**Issue by tty061** [sensu-plugins/sensu-plugins-logstash#25]
Multiple pipeline feature was available at logstash v6, and then a JSON format of a monitoring API response was changed.

Metrics for each pipeline appear as children of '.pipelines' object, while the only pipeline appeared as '.pipeline' at logstash v5.
Also total events metrics over all pipeline was added.

**Comment by majormoses** [comment]
closed via #28 

released: https://rubygems.org/gems/sensu-plugins-logstash/versions/2.1.0
