### ISSUE TITLE
Add support for tcp output

### ISSUE THREAD

**Issue by marji** [sensu-plugins/sensu-plugins-logstash#7]
Could you please add also TCP support (ideally with optional TLS).
The current version supports only two types of output: redis and udp.

Justification: udp - packets / events can be lost on the way. Redis - not everyone uses redis as their entry point (I myself have an ELB in front of a pair of logstash shippers pre-processing/tagging events, storing then in Amazon SQS).

**Comment by marji** [comment]
I don't know anything about ruby, nevertheless, I prepared a super simple PR #8 which adds support for streaming data to logstash via TCP.

I'm not sure whether this could introduce problems on a busy sensu server, e.g. if the logstash tcp endpoint was refusing connection / timeouting.

**Comment by sstarcher** [comment]
#8 fixes
